### ISSUE TITLE
validate block + transaction

### ISSUE THREAD

**Issue by JakubMar** [JakubMar/PA193_test_parser_dash#13]

**Comment by bencikpeter** [comment]
- [x] Merkle tree


- [x] Coinbase

- [x] Refactor timestamp

- [x] First block validation hash NULL

- [ ] Maybe : Check that nLockTime <= INT_MAX[1], size in bytes >= 100[2],

- [x]  status output validator
- [ ] difficulty checker

**Comment by bencikpeter** [comment]
the way how the validator works we cannot validate the first block - it takes references - we might pass the same block twice and threat the case as the first block but that's kinda ugly

**Comment by JakubMar** [comment]
Iteratively set all blocks isValid message to "invalid previous block" after first invalid block
